# -*- coding: utf-8 -*-
"""Untitled103.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VjSodgf1IzRznfwrnaws2esjPGdSx79U
"""

books = []
while True:
  print("\n--- Library System ---")
  print("1. Add Book")
  print("2. View all books")
  print("3. Search book by title")
  print("4. Exit")

  choice = input("Enter your choice (1-4) : ")

  if choice == "1":
    title = input("enter book title :")
    author = input("enter book author : ")
    book_id = input("enter book id :")

    book = {
        "title" : title,
        "author" : author,
        "book_id" : book_id
    }
    books.append(book)
    print("book added successfully")

  elif choice == "2":
    if len(books) == 0:
      print("no books found")
    else:
      print("\n--- All Books ---")
      for book in books:
        print(f"Title : {book['title']}")
        print(f"Author :  {book['author']}")
        print(f"book id : {book['book_id']}")
        print("--------------------")

  elif choice == "3":
    search_title = input("enter book title to search:")
    found = False
    for book in books:
      if book["title"].lower() == search_title.lower():
        print("\n--- Book Found ---")
        print(f"Title : {book['title']}")
        print(f"Author: {book['author']}")
        print(f"book id : {book['book_id']}")
        found = True
        break

    if found == False:
      print("book not found")


  elif choice == "4":
    print("Exiting the library system. Goodbye!")
    break

  else:
    print("invalid")



# print on the same line